// Tests
export const INVALID_NUMERIC_VALUE = 'invalid';
export const VALID_TEXT_VALUE = 'This is a demo text';
export const VALID_UNFORMATTED_NUMERIC_VALUE = 100;
export const VALID_UNFORMATTED_NUMERIC_STRING = '100';
export const VALID_UNFORMATTED_DECIMAL_VALUE = 100.42;
export const VALID_UNFORMATTED_THOUSAND_NUMERIC_VALUE = 100000;
export const VALID_UNFORMATTED_THOUSAND_DECIMAL_VALUE = 100000.42;
export const VALID_UNFORMATTED_THOUSAND_NUMERIC_STRING = '100000';
// FR
export const VALID_FR_FORMATTED_CURRENCY_VALUE = '100\u00A0$';
export const VALID_FR_FORMATTED_NUMERIC_STRING = '100';
export const VALID_FR_FORMATTED_CURRENCY_DECIMAL_VALUE = '100,42\u00A0$';
export const VALID_FR_FORMATTED_THOUSAND_CURRENCY_VALUE = '100\u00A0000\u00A0$';
export const VALID_FR_FORMATTED_THOUSAND_NUMERIC_VALUE = '100\u00A0000';
export const VALID_FR_FORMATTED_THOUSAND_DECIMAL_VALUE = '100\u00A0000,42';
// EN
export const VALID_EN_FORMATTED_CURRENCY_VALUE = '$100';
export const VALID_EN_FORMATTED_NUMERIC_STRING = '100';
export const VALID_EN_FORMATTED_CURRENCY_DECIMAL_VALUE = '$100.42';
export const VALID_EN_FORMATTED_THOUSAND_CURRENCY_VALUE = '$100,000';
export const VALID_EN_FORMATTED_THOUSAND_NUMERIC_VALUE = '100,000';
export const VALID_EN_FORMATTED_THOUSAND_DECIMAL_VALUE = '100,000.42';

// utils
export const FR = 'FR';
export const EN = 'EN';
